# Generated by Django 5.2.6 on 2025-09-06 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address to be blocked', unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the IP was blocked')),
                ('reason', models.CharField(blank=True, help_text='Reason for blocking this IP', max_length=255)),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'db_table': 'ip_tracking_blockedip',
                'ordering': ['-created_at'],
            },
        ),
    ]
